### ISSUE TITLE
@allen501pc 無法增加新成員

### ISSUE THREAD

**Issue by ilyalee** [hhfunds/dadumt#12]
結果是 @allen501pc 仍然是 outside collaborator，還沒有回應加入 organisation 的邀請。

![screen shot 2016-08-01 at 11 44 48 pm](https://cloud.githubusercontent.com/assets/1282380/17299872/9663e052-5842-11e6-9a64-ec58ae260f84.png)
![screen shot 2016-08-01 at 11 44 19 pm](https://cloud.githubusercontent.com/assets/1282380/17299873/966eefce-5842-11e6-9939-561057a95938.png)

**Comment by allen501pc** [comment]
Added.

**Comment by allen501pc** [comment]
![image 25](https://cloud.githubusercontent.com/assets/73607/17300353/97b2f87e-5844-11e6-93de-90b6d7aeb207.png)
可以送出邀請。
