### ISSUE TITLE
開放資料平台「組織」清單中尚有掛零的分項計畫

### ISSUE THREAD

**Issue by ilyalee** [hhfunds/dadumt#4]
其他分項計畫資料尚未上傳到資料平台：P1 P2 P3 目前資料都掛零。
以本計劃 P1 為例，需要上傳的網址、帳密（如果有的話）。

網址為：https://data.testdadumt.honghuafund.org/organization
![screen shot 2016-07-31 at 11 22 16 pm](https://cloud.githubusercontent.com/assets/1282380/17277451/acee410a-5775-11e6-9922-5296233bcce9.png)

**Comment by allen501pc** [comment]
生物監測暨生態保育主題提供的資料集，被誤放到產業資源調查主題，現在已經更正回來了。

歷史與人文主題的部分，其實資料集已經放上去了。但是該助理選擇封閉式授權不開放，所以才會顯示0個資料集。必須在登入後才看得到資料集。
一般來說，不太可能選擇不公開才對。正在詢問該主題的助理詳細原因。

**Comment by allen501pc** [comment]
已經詢問完畢，可以設定為公開。

**Comment by ilyalee** [comment]
請於資料集數目更新完畢後，提供新的 screenshot 然後再結案，這樣就有完整的紀錄。感謝！

**Comment by allen501pc** [comment]
![image 24](https://cloud.githubusercontent.com/assets/73607/17300210/ff9ca1ac-5843-11e6-919b-68393dd4bc14.png)
Done!
