### ISSUE TITLE
開放資料平台「關於」頁面相關說明增添更新

### ISSUE THREAD

**Issue by ilyalee** [hhfunds/dadumt#6]
「關於」頁面應該有更完整的說明。
請以子計畫六的相關內容更新即可。

網址為：https://data.testdadumt.honghuafund.org/about
![screen shot 2016-07-31 at 11 30 55 pm](https://cloud.githubusercontent.com/assets/1282380/17277507/2465b974-5777-11e6-8a1c-e80b9a35de47.png)

**Comment by allen501pc** [comment]
已經加入說明文字如下：

本子計畫的目的在於建立一個人文的、生態的、產業的，且具備社會關懷的大肚山資訊平台，作為其他子計畫所建立之資料與成果的彙集點，提供大肚山利害關係人資訊交流的平台。

此外，此一資訊平台在整合大肚山各子計畫相關的研究成果與資料後，如何將蒐集到的資料整合成開放資料(Open Data)，使得這些資料能夠容易地被加值再利用，也是另一個重要的課題。在現有的資料開放平台中，由政府推動的「政府資料開放平台」是一個典型的案例。

因此，本子計畫也將建置與開發相關開放資料(Open Data)平台，逐一規劃此一開放資料共享平臺。藉由此計畫的推動，將此一開放資料平台作為開放原始碼專案釋出，以提供後續更多加值應用的開發。
