### ISSUE TITLE
存取資料集預覽時畫面空白

### ISSUE THREAD

**Issue by ilyalee** [hhfunds/dadumt#7]
存取 P2 大肚山生物水域調查(2016年6月) 相關資料集時，發現預覽畫面一片空白。
不曉得是個別問題還是普遍問題。

網址：https://data.testdadumt.honghuafund.org/dataset/biologicalsurvey201606/resource/1b896c12-abfb-4be8-956d-aacf69182d72?view_id=05412917-eded-4a5d-abe2-f4ffcc079fde
![screen shot 2016-07-31 at 11 38 19 pm](https://cloud.githubusercontent.com/assets/1282380/17277546/f2529820-5777-11e6-9985-5e2e1c462f6b.png)

**Comment by ilyalee** [comment]
瀏覽其他分項計畫資料也有同樣情形。

![screen shot 2016-07-31 at 11 48 14 pm](https://cloud.githubusercontent.com/assets/1282380/17277593/4f50dcfc-5779-11e6-954b-2993e3e5a1db.png)

**Comment by allen501pc** [comment]
忘了掛上 Data Preview 模組。正在處理中。

**Comment by allen501pc** [comment]
正式站台可以work:
https://data.dadumt.honghuafund.org/dataset/environmentsurvery201606/resource/9c05a5bf-73c9-437b-94a8-32cbe5b1234b
