### ISSUE TITLE
如何替資料集上標籤？

### ISSUE THREAD

**Issue by ilyalee** [hhfunds/dadumt#9]
![screen shot 2016-08-01 at 12 09 34 am](https://cloud.githubusercontent.com/assets/1282380/17277716/4c43d41c-577c-11e6-96c2-e09469487a20.png)

**Comment by allen501pc** [comment]
請以之前發放的總計畫CKAN帳號密碼登入後，點選要修改的資料集，右上角有個「管理」點進去就可以加入標籤欄位了。

**Comment by ilyalee** [comment]
可以再重寄一次嗎？（總計畫 CKAN 密碼）

**Comment by allen501pc** [comment]
已經寄信。Closed it.
